status = [
  "ci",
  "ci (x86_64-linux)",
  "ci (x86_64-darwin)",
  "build (8.10.7, ubuntu-latest)",
  "build (8.10.7, windows-latest)",
  "build (9.2.5, ubuntu-latest)",
  "build (9.2.5, windows-latest)",
]
timeout_sec = 10800
required_approvals = 1
block_labels = [ "WIP", "DO NOT MERGE" ]
delete_merged_branches = true
cut_body_after = "# Checklist"
